[Settings]
ID = "1a75b53a-1cab-4f44-94eb-e714a3bacb08"


# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
 # This is the directory to change to before starting a build.
 base  = "safespace/"
 # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
 # This is the directory that you are publishing from (relative to root of your repo)
 publish = "safespace/build/"
 # This will be your default build command
 command = "yarn build"